
keys:
  - &admin_tim age1az28qfxahja456lhj2hwedypc85852c0upn3achn5jw83a76uvqsxl6t9v
  - &server_wazuh age1rdlsvrt92lsyglg5cxd2vpgj56rg4u6qw2wvlkesgcxy3a93ksnqmfran9
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_tim
      - *server_wazuh
